
Showing logs for build [32mablazleon-jxpy-pr-18-pr-build-wf5dq-1[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-zp9qr[0m
{"level":"info","ts":1593186680.0369892,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/0.8.0-ns-support: no such file or directory"}
{"level":"info","ts":1593186680.0377295,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mablazleon-jxpy-pr-18-pr-build-wf5dq-1[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-j9dqh[0m
{"level":"info","ts":1593186681.0015342,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1593186681.0041635,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mablazleon-jxpy-pr-18-pr-build-wf5dq-1[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m

Showing logs for build [32mablazleon-jxpy-pr-18-pr-build-wf5dq-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-ablazleon-jxpy-pr-18-pr-build-wf5dq-x9ntb[0m
{"level":"info","ts":1593186688.272283,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/0.8.0-ns-support: no such file or directory"}
{"level":"info","ts":1593186689.6055422,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/*********/**py.git @ master in path /workspace/source"}

Showing logs for build [32mablazleon-jxpy-pr-18-pr-build-wf5dq-1[0m stage [32mfrom-build-pack[0m and container [32mstep-setup-builder-home[0m

Showing logs for build [32mablazleon-jxpy-pr-18-pr-build-wf5dq-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:2333da0fe173707c7216a2ce92bf4cf3b0e1c806,18:0f32b5c27c51b319f098a729c9fa37749a768bee
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git fetch origin --unshallow 0f32b5c27c51b319f098a729c9fa37749a768bee: 2333da0fe173707c7216a2ce92bf4cf3b0e1c806:
DEBUG: ran git fetch --unshallow origin 0f32b5c27c51b319f098a729c9fa37749a768bee: 2333da0fe173707c7216a2ce92bf4cf3b0e1c806: in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git branch
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git checkout master
DEBUG: ran git checkout master in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git reset --hard 2333da0fe173707c7216a2ce92bf4cf3b0e1c806
DEBUG: ran git reset --hard 2333da0fe173707c7216a2ce92bf4cf3b0e1c806 in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git clean -fd .
DEBUG: ran clean --force -d . in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git merge 0f32b5c27c51b319f098a729c9fa37749a768bee
DEBUG: ran git merge 0f32b5c27c51b319f098a729c9fa37749a768bee in 
DEBUG: JX_LOG_LEVEL=error LC_ALL=C git log --format=%H%x1f%an%x1f%ae%x1f%cn%x1f%ce%x1f%s%n%b%x1e 2333da0fe173707c7216a2ce92bf4cf3b0e1c806..HEAD
Merged SHA 0f32b5c27c51b319f098a729c9fa37749a768bee with commit message 'Update requirements.txt' into base branch master

Showing logs for build [32mablazleon-jxpy-pr-18-pr-build-wf5dq-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Showing logs for build [32mablazleon-jxpy-pr-18-pr-build-wf5dq-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
E0626 15:51:33.645002       9 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
[36mINFO[0m[0001] Using dockerignore file: /workspace/source/.dockerignore 
[36mINFO[0m[0001] Retrieving image manifest python:onbuild     
E0626 15:51:34.114055       9 metadata.go:154] while reading 'google-dockercfg' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg
E0626 15:51:34.118013       9 metadata.go:166] while reading 'google-dockercfg-url' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg-url
[36mINFO[0m[0002] Retrieving image manifest python:onbuild     
[36mINFO[0m[0003] Built cross stage deps: map[]                
[36mINFO[0m[0003] Retrieving image manifest python:onbuild     
[36mINFO[0m[0004] Retrieving image manifest python:onbuild     
[36mINFO[0m[0005] Executing 3 build triggers                   
[36mINFO[0m[0005] Checking for cached layer gcr.io/envjenkinsk8udacitycapstone/cache:16e5d4381a19bb1839ed70d19ca4239f2c7c99129be32d7dfc4394b4a89aebcc... 
[36mINFO[0m[0005] No cached layer found for cmd COPY requirements.txt /usr/src/app/ 
[36mINFO[0m[0005] cmd: EXPOSE                                  
[36mINFO[0m[0005] Adding exposed port: 8080/tcp                
[36mINFO[0m[0005] Unpacking rootfs as cmd COPY requirements.txt /usr/src/app/ requires it. 
[36mINFO[0m[0022] COPY requirements.txt /usr/src/app/          
[36mINFO[0m[0022] Resolving 1 paths                            
[36mINFO[0m[0022] Taking snapshot of files...                  
[36mINFO[0m[0022] RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0022] Taking snapshot of full filesystem...        
[36mINFO[0m[0022] Pushing layer gcr.io/envjenkinsk8udacitycapstone/cache:16e5d4381a19bb1839ed70d19ca4239f2c7c99129be32d7dfc4394b4a89aebcc to cache now 
[36mINFO[0m[0025] Resolving 27638 paths                        
[36mINFO[0m[0031] cmd: /bin/sh                                 
[36mINFO[0m[0031] args: [-c pip install --no-cache-dir -r requirements.txt] 
[36mINFO[0m[0031] Running: [/bin/sh -c pip install --no-cache-dir -r requirements.txt] 
Collecting pylint==pylint==2.5.3 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement pylint==pylint==2.5.3 (from -r requirements.txt (line 1)) (from versions: 0.15.2, 0.16.0, 0.18.0, 0.18.1, 0.19.0, 0.20.0, 0.21.0, 0.21.1, 0.21.2, 0.21.3, 0.22.0, 0.23.0, 0.24.0, 0.25.0, 0.25.1, 0.25.2, 0.26.0, 0.27.0, 0.28.0, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 2.0.0.dev0, 2.0.0.dev1, 2.0.0.dev2, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0.dev0, 2.3.0.dev1, 2.3.0.dev2, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.5.3)
No matching distribution found for pylint==pylint==2.5.3 (from -r requirements.txt (line 1))
You are using pip version 10.0.1, however version 20.2b1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
[31m
Pipeline failed on stage 'from-build-pack' : container 'step-build-container-build'. The execution of the pipeline has stopped.[0m
